Overhaul list display of mods + add download counts and external links
ryanccn/moddermore pull request #35
Opened 2022-10-22 13:08 UTC by lporu

Some small changes to the way mods are displayed in a list to make it easier to edit in manual mode, by adding external links to the original mod pages and adding a download count to all mods. Inspired by the way modrinth displays the mods on their site.

![Screenshot 2022-10-11 at 13 43 31](https://user-images.githubusercontent.com/116395651/197340651-fa19ba1e-1a08-47f1-a1a9-8251b629fad1.png)

Signed-off-by: lporu <116395651+lporu@users.noreply.github.com>

2022-10-24 06:53 UTC, ryanccn requested changes
Overall great stuff, just a few little changes and it's good to go! Thanks 😃

2022-10-24 06:53 UTC, ryanccn commented on src/components/partials/RichModDisplay.tsx
> +              src={data.iconUrl}
might want to add `width` and `height` attributes here to prevent layout shift

2022-10-24 06:53 UTC, ryanccn commented on src/components/partials/RichModDisplay.tsx
> +          <div className="min-w-fit text-right">
on mobile this is still rendered right to the description, resulting in it being a bit squished; could you move it to be displayed under the description (like Modrinth does) on mobile?

2022-10-26 11:24 UTC, lporu commented
Moved the download count + button on smaller screens (mobile) and added the `width` and `height` attributes to mod icons. Should now feel much better on mobile screens.

2022-10-27 04:48 UTC, ryanccn approved these changes
Looks great!

2022-10-27 04:48 UTC, merged