Fix: List updating
ryanccn/moddermore pull request #421
Opened 2024-10-13 15:13 UTC by SeaSide53

Now that we validate request strictly, when sending extra data, the validation would fail. This disabled editing lists.
Now we only send the required data and no more fixing the issue.

2024-10-21 01:59 UTC, ryanccn requested changes
Please resolve the DCO issues!

2024-10-27 15:28 UTC, SeaSide53 commented
Sorry, fixed it.

2024-10-31 01:06 UTC, ryanccn approved these changes

2024-10-31 01:07 UTC, merged

2024-10-31 01:07 UTC, ryanccn commented
Thank you!